name: Node.js CI

on:
  push:

jobs:
  lint-nodejs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        working-directory: [backend, frontend]
        node-version: [18]

    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - name: Checkout code at ${{ matrix.working-directory }}
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        if: always()
        run: npx prettier --check .

      - name: ESLint
        if: always()
        run: npx eslint .

      - name: build
        if: always()
        run: npm run build
